### ISSUE TITLE
Student does not see the image when activity is restricted

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-format_vsf#10]
@gjb2048 could you please take a look at this issue, it did work before but I think because of the 'hand' development we accedentily broke the feature? 

I created a video for clarification: https://ltnc.screencasthost.com/watch/cZju2OVRjhH

But what happens is that as a student you don't see the image anymore, see below. I did notice in the 'consule' it appears to show a 303 error. BUt since I could replicated it on a different moodle I don't think it is a server issue by default. 
![image](https://github.com/user-attachments/assets/7e54442a-b507-4bd2-9e12-e44c45a93d20)

This is how it supose the look
![image](https://github.com/user-attachments/assets/8c553e05-be12-420c-9278-c4d6ada199f1)

Hope you can find the problem and resolve it quickly 
Thanks Gemma 

@servicedeskltnc

**Comment by gemguardian** [comment]
@gjb2048 just to be sure: we used this branche https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/tree/MOODLE_400_401

**Comment by gjb2048** [comment]
Hi @gemguardian 

Odd.  Ok a 303 is https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303 - so what is the contents of such in the 'response' of the file in the browser network panel?  I did notice in your screencast (2:06) that the 'Facebook' image on the login index page also isn't served.  So I'm not convinced this is a format issue, rather a server configuration issue.

G

**Comment by gjb2048** [comment]
Also this https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/MOODLE_400_401/lib.php#L825 is where the file is sent from.  I'll compare with other similar code.

**Comment by gemguardian** [comment]
@gjb2048 at first I was also not convinced that it was a coding issue but a server issue. I tested it on a different server, and we had a similar issue that's why I swant to be check this with you as well. 

The server tech guys (of course) point to the code :P (always funny)

**Comment by gjb2048** [comment]
I've tried to find https://samenierenmetltnc.nl/ to look at the login page as that's related possibly but can't find that server.

**Comment by gjb2048** [comment]
Is there a similar 303 on the login page before you login?

**Comment by gemguardian** [comment]
https://samenlerenmetltnc.nl/<https://samenlerenmetltnc.nl/my/courses.php> is the correct link

you can login with xxxxxx xxxxx


Warme groet,


[cid:7a02a2ed-e41a-41ec-93bf-96354a1c9537] Gemma Lesterhuis-Couwenberg

Eigenaar & Moodle LMS Gespecialiseerd Functioneel -en Applicatiebeheer


[image5.png] <https://ltnc.nl/>
Tel: (085) 130 52 99
Web: https://ltnc.nl<https://ltnc.nl/>

Liever online sparren?
Boek een afspraak met een van onze ***@***.***/bookings/>

Up to date blijven?
Schrijf je dan in voor de nieuwsbrief<https://ltnc.email-provider.eu/memberforms/subscribe/standalone/form/?a=yiiksffdyu&l=gwwoekpd2p> of volg ons op LinkedIn<https://nl.linkedin.com/company/lesterhuis-training-en-consultancy?trk=public_profile_topcard-current-company>!

Zaalstraat 3A 5595 GH  LEENDE


________________________________
Van: Gareth J Barnard ***@***.***>
Verzonden: woensdag 28 augustus 2024 17:30
Aan: Lesterhuis-Training-en-Consultancy/moodle-format_vsf ***@***.***>
CC: Gemma Lesterhuis | LTNC ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Lesterhuis-Training-en-Consultancy/moodle-format_vsf] Student does not see the image when activity is restricted (Issue #10)


I've tried to find https://samenierenmetltnc.nl/ to look at the login page as that's related possibly but can't find that server.

**Comment by gemguardian** [comment]
> Is there a similar 303 on the login page before you login?

Not there is none. 

I don't think it's server releated, because when you **remove** the restriction from the activity it simply shows the image. 
It makes sense from a Moodle premission point of view that you would not see the image because you don't have premission as a student to see restricted activities. 

BUt I have no clue how we avoided this issues when we used the 'stopsignes' because that does not work either anymore and did before. Maybe PHP related?

**Comment by gjb2048** [comment]
Ok, this:

![Screenshot 2024-08-28 164101](https://github.com/user-attachments/assets/73dbeafa-8037-4441-891c-791dc8b3633d)

is what the server is sending instead of the image.

**Comment by gjb2048** [comment]
Need to think as being redirected.

**Comment by gjb2048** [comment]
Ok, not a solution but could be in the right direction as the sending code should be calling 'send_file_not_found()', instead of returning false.  If then get a 404 then that would indicate that for some reason https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/MOODLE_400_401/lib.php#L820 has failed to find the file in on the server because we know that 'modicon', 'https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/MOODLE_400_401/lib.php#L802' is in the URL path.  That icon could have not been restored / backed up on that course?

**Comment by gemguardian** [comment]
@gjb2048 no it was not a backup/restore action. I am sure of that.

**Comment by gjb2048** [comment]
@gemguardian Just comited https://github.com/gjb2048/moodle-format_vsf/commit/f8065c1ed41d87cc83d2747169decfd23589403f - and that will give 404's instead if theory is correct and then related to #8 and #9.

Will also attempt fix of CI issue, https://github.com/gjb2048/moodle-format_vsf/actions/runs/10600153659/job/29376913716 etc.

**Comment by gjb2048** [comment]
@gemguardian RE "no it was not a backup/restore action. I am sure of that." in relation to the course not being restored on that server with that icon, so possibly the backup file from a time before #8 / #9 was implemented.

**Comment by gjb2048** [comment]
@gemguardian I hope you don't mind but I've edited your message to remove the login username / password from your comment as this issue is public.  I've made a note locally.

**Comment by gemguardian** [comment]
> @gemguardian I hope you don't mind but I've edited your message to remove the login username / password from your comment as this issue is public. I've made a note locally.

No problem!

**Comment by gemguardian** [comment]
> @gemguardian Just comited [gjb2048@f8065c1](https://github.com/gjb2048/moodle-format_vsf/commit/f8065c1ed41d87cc83d2747169decfd23589403f) - and that will give 404's instead if theory is correct and then related to #8 and #9.
> 
> Will also attempt fix of CI issue, https://github.com/gjb2048/moodle-format_vsf/actions/runs/10600153659/job/29376913716 etc.

Updated the version, but has not resolved the issue. I am logging off now, I will be back online tomorrow at the end of the day.

**Comment by gjb2048** [comment]
@gemguardian Would it be possible to eMail me a copy of the course to test as a student locally please?  Then if I can replicate locally then I can attach the debugger and investigate.  Will also see if I can make local course replicate.

**Comment by gjb2048** [comment]
@gemguardian Interesting, I can replicate locally!  On the case.

**Comment by gjb2048** [comment]
@gemguardian Found it! -> https://github.com/gjb2048/moodle-format_vsf/commit/e3364e9578b8783f4a2f769ce5b11b4f1a79db9a - also improved to ensure correct context in line with pluginfile pattern of other plugins -> https://github.com/gjb2048/moodle-format_vsf/commit/d2bdd9e087d8013af76d94843fea888695fa7979.  Send 'send_file_not_found()' calls are still valid.

**Comment by gjb2048** [comment]
@gemguardian I've now improved the fix by putting the check back in -> https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/commit/320292d3cfe29e7b8651cf7b6320bdfa6abe19a6 - but altering the parameters.  The reason it was failing was because access was being checked against the course module (cm) instead of the course itself.  Thus as there was an activity restriction then that said 'no' before the file was even served.

Looking at:

```
/**
 * This function checks that the current user is logged in and has the
 * required privileges
 *
 * This function checks that the current user is logged in, and optionally
 * whether they are allowed to be in a particular course and view a particular
 * course module.
 * If they are not logged in, then it redirects them to the site login unless
 * $autologinguest is set and {@link $CFG}->autologinguests is set to 1 in which
 * case they are automatically logged in as guests.
 * If $courseid is given and the user is not enrolled in that course then the
 * user is redirected to the course enrolment page.
 * If $cm is given and the course module is hidden and the user is not a teacher
 * in the course then the user is redirected to the course home page.
 *
 * When $cm parameter specified, this function sets page layout to 'module'.
 * You need to change it manually later if some other layout needed.
 *
 * @package    core_access
 * @category   access
 *
 * @param mixed $courseorid id of the course or course object
 * @param bool $autologinguest default true
 * @param object $cm course module object
 * @param bool $setwantsurltome Define if we want to set $SESSION->wantsurl, defaults to
 *             true. Used to avoid (=false) some scripts (file.php...) to set that variable,
 *             in order to keep redirects working properly. MDL-14495
 * @param bool $preventredirect set to true in scripts that can not redirect (CLI, rss feeds, etc.), throws exceptions
 * @return mixed Void, exit, and die depending on path
 * @throws coding_exception
 * @throws require_login_exception
 * @throws moodle_exception
 */
function require_login($courseorid = null, $autologinguest = true, $cm = null, $setwantsurltome = true, $preventredirect = false) {
```

Then I've chosen to not redirect but tell Moodle to report some sort of error (as it does somehow) if the URL is invalid due to the session not having permission.

G

**Comment by gjb2048** [comment]
Like this when using the URL and not got access to the course:

![Screenshot 2024-08-28 182629](https://github.com/user-attachments/assets/539d9332-4809-477e-9e78-9793426455ad)

**Comment by gemguardian** [comment]
@gjb2048 we are almost there. I can see the image now as a **student**, but the image is not 'blurred' out while being restricted. 

It does show properly as an admin though :)

![image](https://github.com/user-attachments/assets/dc913f47-cca3-41fe-92e2-18f6c1324d8b)

**Comment by gjb2048** [comment]
@gemguardian 

The opacity that blurs the image has been set to operate on the CSS class 'conditionalhidden', this is only added by the core code (textclasses) by the logic:

![Screenshot 2024-08-28 232935](https://github.com/user-attachments/assets/756b08b0-7392-4665-9e65-d8358dba0527)

Will investigate a solution tomorrow.

**Comment by gjb2048** [comment]
@gemguardian Opacity fixed in https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/commit/16e46467e4039b589a4be555404b1b149478941a - please update.

**Comment by gemguardian** [comment]
@gjb2048 thank you, I did had to do a server cach clear before it appeared but that's just loving Moodle right now. 

Could you please patch this trhough to the 4.02, 4.03 and the master branch?

**Comment by gjb2048** [comment]
@gemguardian All forward ported.

**Comment by gemguardian** [comment]
@gjb2048 thank you - I am a little bit behind due to holidays - testing our new notification system i.t.m.

**Comment by gjb2048** [comment]
@gemguardian No worries :) - i.t.m?

**Comment by gemguardian** [comment]
Your document has been completed 

VIEW COMPLETED DOCUMENT 
***@***.***
All parties have completed Please DocuSign: 
Once you sign this it will go on for final signature.
Do Not Share This EmailThis email contains a secure link to DocuSign. Please do not share this email, link, or access code with others.
Alternate Signing MethodVisit DocuSign.com, click 'Access Documents', and enter the security code:F487CE2C6DEF479FB5ECF88F426130293 
About DocuSign
Sign documents electronically in just minutes. It's safe, secure, and legally binding. Whether you're in an office, at home, on-the-go -- or even across the globe -- DocuSign provides a professional trusted solution for Digital Transaction Management™. 
Questions about the Document?If you need to modify the document or have questions about the details in the document, please reach out to the sender by emailing them directly.Stop receiving this email
Report this email
 or read more about Declining to sign
 and Managing notifications.
If you are having trouble signing the document, please visit the Help with Signing
 page on our Support Center.

Download the DocuSign App 
This message was sent to you by Sharilyn Berry who is using the DocuSign
 Electronic Signature Service. If you would rather not receive email from this sender you may contact the sender with your request.
