### ISSUE TITLE
VSF version 3.9.0.2 and 4.0.0.2 (probably in versions between as well) | Progressbar does not show the right completion %

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-format_vsf#2]
We reproduced this issue by placing 6 activities in 1 section, with on the 2th till 6th an activity restriction. 
We had a student enrolled, and we had manually completed 3 of the 6 activities for this student.
With the restriction on the 4th till 6th the progress bar in the section shows 60%, when we remove the restrictions on the 4th till 6th the progress bar shows 50% as it is expected. 

We have created a video for more detail and better explaination: https://vimeo.com/788397651/014c2a4fb2

**THIS ISSUE IS CREATED SO IT HAS A CONNECTION TO OUR SERVICEDESK**

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/helpdesk/tickets/14580" target="_blank">14580</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/helpdesk/tickets/14580" target="_blank">#14580</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by gjb2048** [comment]
Hi @gemguardian,

I see, humm, not sure.  Ok, this is the code that does the calculation of the percentage: https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/master/classes/output/renderer.php#L397-L479.

To try and understand the issue more, is there a correlation / impact on what the module in terms of its restriction depends on?  i.e. is the percentage different if it depends on a module that has been completed or not?

G

**Comment by gjb2048** [comment]
@gemguardian I think we also need to debug this, so please could you patch your code as follows:

```
//$data->percentlabelvalue = $this->sectioncompletionpercentage[$section->section].'%';
$data->percentlabelvalue = $this->sectioncompletionpercentage[$section->section].'% - C: '.$complete.' - T: '.$total;

```
in effect, this line: https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/master/classes/output/renderer.php#L467 in the M4.0 version please.

**Comment by gemguardian** [comment]
@gjb2048 great I will check tomorrow :)

**Comment by gjb2048** [comment]
Update, can't quite replicate, but interesting for a student whom can see all four but one is restricted, the total should be '4' but is '3', so this means that the code thinks that the module is not 'uservisible' when it is! ->

![Screenshot 2023-01-11 204748](https://user-images.githubusercontent.com/1058419/211914735-ab58e180-d781-4e88-9202-2932f81f89fe.png)

**Comment by gjb2048** [comment]
Hi @gemguardian,

Ok, a bit more debugging with:

```
//error_log($thismod->name.' - visible '.$thismod->visible.' - uservisible: '.$thismod->uservisible.' - visibleoncoursepage: '.$thismod->visibleoncoursepage);
                //if ($thismod->uservisible) {
                if ($thismod->visible) {
```

And... I think its all about if the user can get to the module somehow, i.e. the 'visible' attribute, and not the 'uservisible' / 'visibleoncoursepage' attributes.  Thus even if 'Available but not shown on course page' then the student would still be able to access when they have the link and so in the calculation.  The same goes for all combinations of access restriction where the module until the criteria is satisfied so not 'uservisible' but it is 'visible'.  All very complicated and I'm not 100% certain all of the combinations work, however, please could you test and confirm my findings by changing:

`if ($thismod->uservisible) {`

to

`if ($thismod->visible) {`

being this line: https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/master/classes/output/renderer.php#L421 in the M4.0 version.

**Comment by gemguardian** [comment]
@gjb2048 you are the best! The fixed the issue. I have updated the master on my side, and will paddle back to 3.9

if ($thismod->uservisible) {

to

if ($thismod->visible) {

**Comment by gjb2048** [comment]
@gemguardian Do you need me to do the M3.9 backport?

**Comment by gemguardian** [comment]
I already did on my own branch



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Gareth J Barnard ***@***.***>
Datum: 12-01-2023 19:41 (GMT+01:00)
Aan: Lesterhuis-Training-en-Consultancy/moodle-format_vsf ***@***.***>
Cc: "Gemma J.J. Lesterhuis" ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [Lesterhuis-Training-en-Consultancy/moodle-format_vsf] VSF version 3.9.0.2 and 4.0.0.2 (probably in versions between as well) | Progressbar does not show the right completion % (Issue #2)


@gemguardian<https://github.com/gemguardian> Do you need me to do the M3.9 backport?

**Comment by gjb2048** [comment]
@gemguardian No worries :)

**Comment by gjb2048** [comment]
@gemguardian Just did a 'cherry-pick' of the M3.9 commit on the M3.11 branch for consistency.

**Comment by gemguardian** [comment]
Thank you!



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Gareth J Barnard ***@***.***>
Datum: 12-01-2023 19:51 (GMT+01:00)
Aan: Lesterhuis-Training-en-Consultancy/moodle-format_vsf ***@***.***>
Cc: "Gemma J.J. Lesterhuis" ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [Lesterhuis-Training-en-Consultancy/moodle-format_vsf] VSF version 3.9.0.2 and 4.0.0.2 (probably in versions between as well) | Progressbar does not show the right completion % (Issue #2)


@gemguardian<https://github.com/gemguardian> Just did a 'cherry-pick' of the M3.9 commit on the M3.11 branch for consistency.
