### ISSUE TITLE
M4.1 error | when having module view button NO

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-format_vsf#5]
@gjb2048 when I turn debuggin on I see the following error appearing. When I use the following settings:

- Course Layout : show all sections on one page
- Donut/bar or none: none
- Module view button: no
- Module description tooltip: no

not sure what I am missing but I think it is not that big of a change? 

section_activity_summary() is deprecated. Please use core_courseformat\output\local\content\section to render sections. If you need to modify those information, extend core_courseformat\output\local\content\section\cmsummary in your format plugin.
line 574 of /course/format/classes/output/section_renderer.php: call to debugging()
line 503 of /course/format/vsf/classes/output/renderer.php: call to core_courseformat\output\section_renderer->section_activity_summary()
line 567 of /course/format/vsf/classes/output/renderer.php: call to format_vsf\output\renderer->section_activity_summary()
line 759 of /course/format/vsf/classes/output/renderer.php: call to format_vsf\output\renderer->display_section()
line 66 of /course/format/vsf/format.php: call to format_vsf\output\renderer->multiple_section_page()
line 276 of /course/view.php: call to require()

**Comment by gjb2048** [comment]
@gemguardian All to do with core course format API changes.  I have a fix from Collapsed Topics that I'll transpose.

**Comment by gemguardian** [comment]
@gjb2048 oh that's great if you could do that please :)

**Comment by gjb2048** [comment]
@gemguardian Looks like I already had but is a fault with the code I transposed, now fixed, my bug = no charge.

**Comment by gemguardian** [comment]
@gjb2048 thank you!
