### ISSUE TITLE
Progressbar vs restrictions

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-format_vsf#6]
<p>Hi Gareth,</p><p>we just noticed that in the VSF format the progressbar/circle does not take in consideration that students might not see an activity/resource because it is has an activity restriction: Groups<br><br>Can we take in consideration that when an activity /resource is restricted for a student it does not count in the progress bar/circle?&nbsp;<br><br>I am doubtfull on this one because I can imagine there are situations like: what do you want to happen if it's an activity restriction and the criteria are met, does the completion bar/circle does take it in consideration?&nbsp;<br><br>I am not even sure if this happened due to the changes between 3.9 and 4.1 , as in what did we do before?&nbsp;<br><br>Looking forward to your insights on this quest</p><p>Gemma<br><br>&nbsp;</p> <br/>

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/helpdesk/tickets/20018" target="_blank">20018</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/helpdesk/tickets/20018" target="_blank">#20018</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by gemguardian** [comment]
@gjb2048 not sure if you get a notification if I just create it :)

**Comment by gjb2048** [comment]
@gemguardian Got the notification :) - will look when I can.

**Comment by gjb2048** [comment]
Hi Gemma,

Will be down to this line https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/master/classes/output/renderer.php#L428 and the interpretation of the 'visible' attribute of the cm_info class (I think).  Sections visibility have been problematic in the past, but this is a module and so really will depend on being able to replicate and prove that students whom cannot see the module because of a group restriction still have the progress bar calculated correctly in terms of available modules to complete.  Currently it is my understanding that the 'visible' attribute is calculated correctly for group restrictions, from memory - but hazy.  Has the issue been replicated?

Gareth

**Comment by gjb2048** [comment]
Hi @gemguardian,

It is an instance of 'cm_info':

![Screenshot 2024-01-08 202227](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/assets/1058419/60a99c45-5106-4387-86db-6ddcd4cdc60f)

which also has:

![Screenshot 2024-01-08 202339](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/assets/1058419/e5374a78-ec2e-4cda-8847-9c4e8a6b1c9a)

Thus with the way things work, may need to consider if these attributes need to be used?  But quite possibly they are in the determination of 'visible'.  And it could be that the user can still get to the module even if it's not visible on the course page - i.e. via a link.  Would need to investigate further / see of there is a helper method to be called instead.

Please let me know how much more time you'd like me to spend on this Gemma?

Kind regards,

Gareth

**Comment by gemguardian** [comment]
@gjb2048 if you spend more then 4 hours please check in. Would that work?

**Comment by gjb2048** [comment]
@gemguardian Should do, easily...

Looking further...

![Screenshot 2024-01-08 204304](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/assets/1058419/497a5f4d-a9e1-4c16-a107-c6e3413ca51f)
![Screenshot 2024-01-08 204213](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/assets/1058419/d1d3bda0-7e18-4a56-9dc2-8edc24030dac)
![Screenshot 2024-01-08 204352](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/assets/1058419/725cddb4-7154-4293-9f0d-92276b42847f)

Then perhaps need a change to 'uservisible'.  Do you already have a Moodle instance that replicates this?  If so then does changing 'visible' to 'uservisible' here https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/master/classes/output/renderer.php#L428 make a difference and what steps did you take to replicate please?  If not then what steps should I take to get the same reported scenario please?

Kind regards,

Gareth

**Comment by gemguardian** [comment]
@gjb2048 changing https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/master/classes/output/renderer.php#L428 solve the issue for my 4.1 Moodle. 


Enclosed you find a course backup to replicate the behavior. 
In the backup you have 3 sections and 2 Groups (group 1 and group 2) 

in section 1 you have 2 activities with one restricted for group 2 + section 2 you have 3 activities which 2 have a restriction on group 1. 

all activities have manual completion. You can play with the group restrictions to see how it act (or duplicate activities if you you like). 

**to replicate:**

1. enrol 2 accounts in the role student
2. assign student 1 to group 1 
3. assign student 2 to group 2
4. Log in as student 1
5. confirm you see section 2 Multi-language (V2) 1 activity
6. manually complete the TEST activity and confirm you progressbar is 100%
7. go to section 2
8. confirm you see 3 activities
9. manual complete each activity and check the completion in the progressbar it should go with 33,33% each time
10. Login as student 2
11. confirm you see 1 activity in section 2
12. complete the activity
13. comfirm the progress bar jumps to 100%

**Comment by gemguardian** [comment]
uploading the backup did not work, you can download it here: https://www.ltncbestanden.nl/s/BYnm9hjzPADBwG1T

**Comment by gjb2048** [comment]
Hi @gemguardian 

Fixed in 'master' and 'MOODLE_400_401' branches.

Thanks for the replication instructions, really helped, especially the course.

Kind regards,

Gareth
