### ISSUE TITLE
 version 2024050801: Folder Inline breaks view 

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-format_vsf#7]
@gjb2048 I stumpled on an error when we placed Folder (resource) to display **inline on a course page** 

course_section_cm_name can not be used any more. Please, use core_courseformat\output\local\content\cm\cmname class instead.

Stack trace: 
line 281 of /course/renderer.php: coding_exception thrown
line 303 of /course/format/vsf/classes/course_renderer.php: call to core_course_renderer->course_section_cm_name()
line 449 of /course/format/vsf/classes/course_renderer.php: call to format_vsf_course_renderer->course_section_cm_vsf()
line 563 of /course/format/vsf/classes/course_renderer.php: call to format_vsf_course_renderer->course_section_cm_list_item_vsf()
line 100 of /course/format/vsf/classes/output/format_renderer_migration_toolbox.php: call to format_vsf_course_renderer->course_section_cm_list_vsf()
line 625 of /course/format/vsf/classes/output/renderer.php: call to format_vsf\output\renderer->course_section_cmlist()
line 802 of /course/format/vsf/classes/output/renderer.php: call to format_vsf\output\renderer->display_section()
line 64 of /course/format/vsf/format.php: call to format_vsf\output\renderer->multiple_section_page()
line 348 of /course/view.php: call to require()

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/assets/16559999/e259bbdc-ccc3-4344-b299-c7b7b941eda6)

**Comment by gjb2048** [comment]
This in effect is a 'warning' and addressed in https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/commit/1e537a84d63d3906362c73829e2b38bbfab81dd6.

**Comment by gjb2048** [comment]
Note to @gjb2048 - need to forward port to M4.4 and backport to M4.2 / M4.1.

**Comment by gjb2048** [comment]
@gemguardian All down to the complicated course format API and the code will still operate correctly without this change.

**Comment by gjb2048** [comment]
@gemguardian All done and backported as well as with https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/commit/3d39e205d0fbfaeb65923ed329f4d8d4c0cb19f0 - which is the same sort of thing.

**Comment by gemguardian** [comment]
@gjb2048 thank you - tested it on both 4.3 and 4.4 and worked fine. Don't forget to send the invoice for the work you have done and has not been invoiced yet.
