### ISSUE TITLE
VSF 4.1 > Activity images backup / import

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-format_vsf#8]
Hi @gjb2048 

When we are using the setting Change icon on the activities. And we create a backup and then import the course again (or make a copy of the course) we need to upload the images again. 

Is there away to ensure that the images are part of the backup/import/copy proces in Moodle LMS 

If so how much time does it take you to developed, and backport if from 4.4 > 4.3 > 4.2 > 4.1 branches 

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/assets/16559999/1f1929ec-c497-4ba2-981f-3e2bc06da65f)

**Comment by gjb2048** [comment]
@gemguardian Investigating....

**Comment by gjb2048** [comment]
@gemguardian To be honest, I'm not quite sure.  Moodle backup and restore is extremely difficult to understand.  The closest I've got is attempting to understand the Grid format https://github.com/gjbarnard/moodle-format_grid/blob/main/backup/moodle2/backup_format_grid_plugin.class.php#L70-L71 and also https://github.com/gjb2048/moodle-mod_collaborate_44/blob/week_8_end/backup/moodle2/backup_collaborate_stepslib.php#L75-L87 in a Moodlebites course I facilitate.  There is also the possibility of course module id changing as I think that is somehow used with the area files for 'format_vsf'.

Need to think but at the same time I recommend seeing if there are Backup and Restore experts around to help?

G

**Comment by gemguardian** [comment]
@gjb2048 I will ask Rogier if he can help out with it, or luuk. I know they have more expeirences in this.

**Comment by rogiervandongen** [comment]
@gemguardian (@gjb2048 )
FInally someone who agrees on the B&R being extremely difficult to understand. Eloy (stronk7) seems to think different about that lol.
However, I don't think this specific issue should be that hard to implement. It's just a matter of hooking into the correct places for the B&R process, which can be somewhat tricky, but this should not be rocket science :)

**Comment by gjb2048** [comment]
@rogiervandongen Oh I'd want to 'discuss' with Eloy that it really is!  Other people I've discussed B&R with have thought so too.  Really interested in what you come up with.  I can't quite get my head around the course module id changing, as I think here that there is no separate table that lists the icon changes as a relation to the actual files in the file table.  An that former table would be the source table for the backup, as against, I suspect a more precise set of arguments when stating that the files table is the source table.  And for that to be at the course, rather than section level in the backup, unless there is a module level?

**Comment by gemguardian** [comment]
@gjb2048 Rogier send in a pull request could you please check/merge - I am not that comfortable with Github to get this sorted :)

**Comment by gjb2048** [comment]
Hi Gemma,

Lots on, will do as soon as I can.

G

**Comment by gjb2048** [comment]
@gemguardian I've reviewed https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/pull/9 and @rogiervandongen should be able to see my comments.

**Comment by gjb2048** [comment]
Hi @gemguardian,

Code checks done and integrated.  I've not tested though, just done a visual inspection.

G

**Comment by gemguardian** [comment]
@gjb2048 I have tested the master M4.4 and it worked - could you backport this to the M4.1 version?

**Comment by gjb2048** [comment]
@gemguardian All, done, hopefully works.

**Comment by gemguardian** [comment]
@gjb2048 thank you it works !
